version: '2.1'

services:
    postgres_db:
        container_name: chat_db
        image: "postgres:16.2-bookworm"
        environment: 
              - PGUSER=${POSTGRES_USER}
              - POSTGRES_USER=${POSTGRES_USER}
              - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
              - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - ./db:/var/lib/postgresql
        healthcheck:
            test: ["CMD-SHELL","pg_isready"]
            interval: 3s
            timeout: 20s
            retries: 8

    chat_api:
        container_name: chat_api
        build:
            context: ../api
            dockerfile: ../docker/dockerfiles/api
        command: poetry run python3 manage.py runserver 0.0.0.0:4000
        ports:
            - ":4000"
        volumes:
            - ../api:/code
        environment:
            - DB_USER=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - DB_NAME=${POSTGRES_DB}
            - DB_HOST=${POSTGRES_HOST}
            - DB_PORT=5432
        depends_on:
            postgres_db:
                condition: service_healthy
        


    web:
        container_name: chat_react
        build:
            context: ../web
            dockerfile: ../docker/dockerfiles/web
        ports:
            - "5173:5173"
        volumes:
            - ../web:/code
            - /code/node_modules;
        # healthcheck:
        #     test: ["CMD", "curl", "--fail", "http://0.0.0.0:3000"]
        #     interval: 5s
        #     timeout: 10s
        #     retries: 3
        # depends_on:
        #     chat_api:
        #         condition: service_healthy
        tty: true # allow run via exec commands


    nginx:
        container_name: nginx_chat
        build:
            context: ./
            dockerfile: ./dockerfiles/nginx
        restart: always
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./ssl:/etc/nginx/ssl
        ports:
            - "443:443"
            - "80:80"
        depends_on:
            - chat_api

